apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-sql-gateway
  template:
    metadata:
      labels:
        app: flink-sql-gateway
    spec:
      containers:
        - name: sql-gateway
          image: docker.1ms.run/flink:1.13.0
          command: ["./bin/sql-gateway.sh"]
          args: ["start"]
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: hive-config
              mountPath: /opt/flink/conf/hive-site.xml
              subPath: hive-site.xml
            - name: flink-nfs-pvc
              mountPath: /opt/flink/lib/
              subPath: flink/
      volumes:
        - name: hive-config
          configMap:
            name: hive-config
        - name: flink-nfs-pvc
          persistentVolumeClaim:
            claimName: flink-nfs-pvc
