# hadoop-nodemanager.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-nodemanager
  labels:
    app: hadoop
    component: nodemanager
spec:
  serviceName: "hadoop-nodemanager"
  replicas: {{ .Values.replicas.yarn.nodemanager }}
  selector:
    matchLabels:
      app: hadoop
      component: nodemanager
  template:
    metadata:
      labels:
        app: hadoop
        component: nodemanager
    spec:
      containers:
        - name: nodemanager
          image: docker.1ms.run/apache/hadoop:3
          command: ["yarn", "nodemanager"]
          ports:
            - containerPort: 8042
              name: web
            - containerPort: 8040
              name: localizer
          env:
            - name: HADOOP_USER_NAME
              value: "root"
            - name: HDFS_NAMENODE_ADDRESS
              value: "hadoop-namenode:8020"
            - name: HADOOP_CONF_YARN_RESOURCEMANAGER_ADDRESS
              value: hadoop-resourcemanager:8032
            - name: HADOOP_CONF_YARN_RESOURCEMANAGER_SCHEDULER_ADDRESS
              value: hadoop-resourcemanager:8030
            - name: HADOOP_CONF_YARN_RESOURCEMANAGER_RESOURCE_TRACKER_ADDRESS
              value: hadoop-resourcemanager:8031
            - name: HADOOP_CONF_YARN_RESOURCEMANAGER_ADMIN_ADDRESS
              value: hadoop-resourcemanager:8033
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /ws/v1/node/info
              port: 8042
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ws/v1/node/info
              port: 8042
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: hadoop-config
              mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
