---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-nodemanager
  labels:
    app: hadoop
    component: nodemanager
spec:
  type: NodePort
  ports:
    - name: web
      port: 8042
      targetPort: 8042
      nodePort: {{ .Values.port.web.nodemanager }}
  selector:
    app: hadoop
    component: nodemanager