apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oracle23c.fullname" . | trim }}
  labels:
    {{- include "oracle23c.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oracle23c.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oracle23c.selectorLabels" . | nindent 8 }}
          {{- if .Values.pod.labels }}
          {{- toYaml .Values.pod.labels | nindent 8 }}
          {{- end }}
      {{- if .Values.pod.annotations }}
      annotations:
        {{- toYaml .Values.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: oracle23c
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: oracle-listener
              containerPort: 1521
              protocol: TCP
            - name: em-express
              containerPort: 5500
              protocol: TCP
            - name: ords-apex
              containerPort: 8080
              protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- range .Values.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .readOnly }}
            readOnly: true
            {{- end }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.pod.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.pod.readinessProbe | nindent 12 }}
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  pgrep -f ora_pmon > /dev/null
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
      {{- range .Values.volumes }}
      - name: {{ .name }}
      {{- if .configMap }}
      configMap:
        name: {{ .configMap.name }}
      {{- else if .persistentVolumeClaim }}
      persistentVolumeClaim:
        claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.pod.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.pod.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.pod.affinity | nindent 8 }}