image:
  registry: docker.1ms.run
  repository: apache/spark
  tag: 4.1.0-preview4-scala2.13-java17-python3-ubuntu
master:
  replicas: 1
worker:
  replicas: 3
thrift:
  replicas: 0
connect:
  replicas: 1
