apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-pvc
  labels:
    app: hive
spec:
  accessModes:
    - ReadWriteMany  # Hive需要多节点读写
  resources:
    requests:
      storage: 5Gi  # 根据你的需求调整大小
  volumeName: nfs-pv
  storageClassName: nfs-storage