apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv  # PV名称
spec:
  capacity:
    storage: 20Gi  # 存储容量
  accessModes:
    - ReadWriteMany  # 访问模式
  nfs:
    server: master
    path: "/mnt/nfs_share"
  storageClassName: nfs-storage  # 新增存储类，用于PVC绑定
  persistentVolumeReclaimPolicy: Retain  # 新增回收策略，避免数据丢失
