apiVersion: v1
kind: Service
metadata:
  name: hive-server2
spec:
  selector:
    app: hive
    component: server2
  ports:
    - name: jdbc
      port: 10000
      targetPort: 10000
      nodePort: 31001
    - name: webui
      port: 10002
      targetPort: 10002
      nodePort: 31002
  type: NodePort